plan result check

diff --git a/.github/workflows/planner.yaml b/.github/workflows/planner.yaml
--- a/.github/workflows/planner.yaml
+++ b/.github/workflows/planner.yaml
@@ -11,31 +11,31 @@ env:
   TF_TOKEN_app_terraform_io: ${{ secrets.TFE_TOKEN }} # https://developer.hashicorp.com/terraform/cli/config/config-file#environment-variable-credentials
 
 jobs:
-  pr_check:
-    name: pr_check
-    runs-on: ubuntu-latest
-    outputs: # https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs
-      pr: ${{ steps.findPr.outputs.pr }}
-      number: ${{ steps.findPr.outputs.number }}
+  # pr_check:
+  #   name: pr_check
+  #   runs-on: ubuntu-latest
+  #   outputs: # https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs
+  #     pr: ${{ steps.findPr.outputs.pr }}
+  #     number: ${{ steps.findPr.outputs.number }}
 
-    steps:
-      - name: get PR number
-        uses: jwalton/gh-find-current-pr@v1
-        id: findPr
-        if: always() # Pick up events even if the job fails or is canceled.
-        with:
-          state: open
+  #   steps:
+  #     - name: get PR number
+  #       uses: jwalton/gh-find-current-pr@v1
+  #       id: findPr
+  #       if: always() # Pick up events even if the job fails or is canceled.
+  #       with:
+  #         state: open
 
-      - name: PR checker
-        env:
-          PR: ${{ steps.findPr.outputs.pr }}
-        if: ${{ steps.findPr.outputs.pr == '' }}
-        run: echo "There's no pr" && exit 1
+  #     - name: PR checker
+  #       env:
+  #         PR: ${{ steps.findPr.outputs.pr }}
+  #       if: ${{ steps.findPr.outputs.pr == '' }}
+  #       run: echo "There's no pr" && exit 1
 
   build:
     name: Terraform planner
     runs-on: ubuntu-latest
-    needs: pr_check
+    # needs: pr_check
 
     steps:
       - name: Checkout
@@ -47,13 +47,6 @@ jobs:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
           aws-region: ${{ env.AWS_REGION }}
-
-      - name: Set environment variables
-        id: setenv
-        run: |
-          LOCAL_BRANCH_NAME='${{ env.GIT_BRANCH_NAME }}'
-          echo "VPC_NAME=${LOCAL_BRANCH_NAME%/*}" >> $GITHUB_ENV
-          echo 'VPCS=${{ env.VPCS }}' >> $GITHUB_ENV
 
       - name: Terraform format
         id: fmt
@@ -76,32 +69,21 @@ jobs:
           cd trf_cloud
           terraform validate
 
-      # - name: Terraform Plan
-      #   id: plan
-      #   run: |
-      #     echo 'plan<<EOF' >> $GITHUB_OUTPUT
-      #     if [[ "${{ env.VPC_NAME }}" == "all" ]]; then 
-      #       for VPC in ${VPCS//,/ }; do
-      #         cd aws-${VPC}
-      #         terraform plan -out ${VPC}.tfplan
-      #         echo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=- ${VPC} =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $GITHUB_OUTPUT
-      #         terraform show ${VPC}.tfplan -no-color >> $GITHUB_OUTPUT
-      #         cd ..
-      #       done
-      #     else
-      #       cd aws-${VPC_NAME}
-      #       terraform plan -out ${VPC_NAME}.tfplan
-      #       echo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=- ${VPC_NAME} =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $GITHUB_OUTPUT
-      #       terraform show ${VPC_NAME}.tfplan -no-color >> $GITHUB_OUTPUT
-      #       cd ..
-      #     fi
-      #     echo 'EOF' >> $GITHUB_OUTPUT
-      #   continue-on-error: true
+      - name: Terraform Plan
+        id: plan
+        run: |
+          cd trf_cloud
+          terraform plan -no-color
+        continue-on-error: true
 
-      # - name: Set sha1 short
-      #   id: sha1 # steps.sha1.outputs.short
-      #   run: |
-      #     echo "short=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
+      - name: check plan outcome
+        run: |
+          1
+          echo {{ steps.plan.outcome }}
+          2
+          echo ${{ steps.plan.outputs.stdout }}
+          3
+          echo ${{ steps.plan.outputs }}
 
       # - name: comment output on PR
       #   uses: actions/github-script@v6
